version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_mcp_record
    environment:
      POSTGRES_DB: aws_mcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: